includes = [
    lib_incs,
    include_directories(
        '.',
        '../Codec',
        '../C_DEFAULT',
    ),
]

c_args = [
    '-DNDEBUG',
]

sources = files(
    'aom_convolve8_neon.c',
    'aom_sum_squares_neon.c',
    'av1_inv_txfm_neon.c',
    'av1_inv_txfm_neon.c',
    'av1_quantize_neon.c',
    'blend_a64_mask_neon.c',
    'block_error_neon.c',
    'cdef_block_neon.c',
    'cdef_filter_block_neon.c',
    'cdef_neon.c',
    'cfl_neon.c',
    'compound_convolve_neon.c',
    'compute_sad_neon.c',
    'convolve_neon.c',
    'convolve_scale_neon.c',
    'dav1d_asm.S',
    'dav1d_util.S',
    'deblocking_filter_intrinsic_neon.c',
    'encodetxb_neon.c',
    'hadamard_path_neon.c',
    'highbd_blend_a64_mask_neon.c',
    'highbd_convolve_neon.c',
    'highbd_convolve_scale_neon.c',
    'highbd_fwd_txfm_neon.c',
    'highbd_inter_prediction_neon.c',
    'highbd_intra_prediction_neon.c',
    'highbd_inv_txfm_neon.c',
    'highbd_jnt_convolve_neon.c',
    'highbd_loopfilter_neon.c',
    'highbd_pickrst_neon.c',
    'highbd_quantize_neon.c',
    'highbd_sse_neon.c',
    'highbd_variance_neon.c',
    'highbd_warp_plane_neon.c',
    'highbd_wiener_convolve_neon.c',
    'inter_prediction_neon.c',
    'intra_prediction_neon.c',
    'itx.S',
    'obmc_sad_neon.c',
    'obmc_variance_neon.c',
    'pack_unpack_intrin_neon.c',
    'pic_analysis_neon.c',
    'pickrst_neon.c',
    'picture_operators_intrinsic_neon.c',
    'restoration_pick_neon.c',
    'sad_neon.c',
    'selfguided_neon.c',
    'sse_neon.c',
    'subtract_block_neon.c',
    'temporal_filtering_neon.c',
    'transforms_intrin_neon.c',
    'upsampled_pred_neon.c',
    'variance_neon.c',
    'warp_plane_neon.c',
    'wedge_utils_neon.c',
    'wiener_convolve_neon.c',
)

project_libs += static_library('ASM_NEON',
                sources: sources,
                 c_args: c_args,
    include_directories: includes,
                install: false,
)
